# Generated by Django 2.1.2 on 2018-11-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_emaildatabase_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildatabase',
            name='password',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
